### PR TITLE
Fixed odd scrollbar alignment

### PR DESCRIPTION
**Pull request by eldang**
Aha!  I think I figured out the weird scrollbar alignment thing.  The problem seems to have been that we had defined the width of the two major div elements in different ways, which had the same result until the chart gets expanded but then respond differently when a scrollbar becomes necessary.  Specifically:

#console had a width of 240px + a total of 60px of margins and padding outside that
#sidenav had a width of 300px, with all margins and padding being adding _inside_ it by the child elements

Of course, these add up to 300px in both cases, which is why it looked AOK until a scrollbar was needed.  But because #sidenav had no margin or padding of its own to put a scrollbar in, our very smart browsers put one outside its 300px instead.  And that's what pushed everything out of alignment.

So this PR just switches the CSS for #sidenav and its children to define width in the same was as #console, which looks to me like it's resolved the issue.  I strongly recommend testing this on your machine before merging, because I would not be shocked if this plays out differently on Windows and I've only been able to test it on my own laptop.  I have tested it on Firefox and Safari on Mac.

### CODE REVIEW

**Comment by coregis** [comment]
Thanks again for digging into this. I've tested it on my desktop and am still getting some strange behavior wrt the left axis label. When the map first opens and the chart is expanded, all is well:

left_axis_visible

However, when I choose a variable to display, the left axis label vanishes:

left_axis_label_disappears

Also, it looks like you created this branch while I was fixing the bug that prevented the Economically Disadvantaged data from showing:

pct_economic_disadvantage_not_appearing

So I'm thinking we should not merge this PR but I do not know how best to proceed. I heard from Max this morning that we're not going to get any additional data, so I merged my PR this morning. Perhaps kill this scrollbar branch then create a new one from the current Master and reapply your CSS revisions? I will defer to your experience on this.

**Comment by eldang** [comment]
@coregis Oops.  I think I have resolved the last issue by merging your changes into this branch.  I now see % economically disadvantaged when I test this branch locally.

I'm working on the disappearing axis title.  I can't replicate the precise failure mode you're seeing, but I do find that if I make my browser window small enough the left Y axis title disappears altogether.  So I think this is just going to be a matter of tweaking the spacing; possibly accepting a little wasted space on larger screens in exchange for pulling it out from under the sidebar on smaller ones.

**Comment by eldang** [comment]
Oh, man.  The issue seems to be inconsistency about whether browsers treat the scrollbar as counting as part of #sidenav's width or not.  The position of that axis and its label is set relative to the edge of the #sidenav element, so when the scrollbar isn't counted it gets displaced leftwards and ends up hidden under the scrollbar.  I've worked around this by adding another 10px to the rightward displacement (line 551 of functions.js), which works well on my machine but may still not be enough for all browsers.  I'm going to test it in the other browsers I have available now, but please also test this on Windows, including in the exact conditions you took those screenshots from + some other random window sizes.

There's a good chance we'll have to add another 5-10 pixels to that displacement to make this robust, in which case that's safe to do.  If we have to add more than that then we should probably try to fix this in a smarter way to avoid creating a gulf of whitespace on Mac Firefox.

**Comment by eldang** [comment]
I have also added some right-side padding to the Hide Chart link because on some window sizes I was able to get it to partly disappear off the edge.  Hopefully that won't make it run into any other elements.

**Comment by coregis** [comment]
By Jove, I think you've done it! I could not replicate the earlier behavior in Chrome or Firefox, so I think we're good to go.

**Pull request merged**
